[package]
name = "simple_api_maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustbreak = {version = "2", features = ["ron_enc"]}
lazy_static = "1.4.0"
